# Generated by Django 5.1.2 on 2024-11-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='question_time_limit',
        ),
        migrations.AddField(
            model_name='quiz',
            name='are_questions_timed',
            field=models.BooleanField(default=False),
        ),
    ]
