# Generated by Django 5.1.2 on 2025-01-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.CharField(default='q65435b43a9cb429a89d7d4fb1eaad6a4', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sharedquiz',
            name='id',
            field=models.CharField(default='sh8a51592386644e2ba6c1a1a235d815ec', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='u1a5170be7b604ca7b6da608d92f153a4', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
