# Generated by Django 5.1.2 on 2025-01-20 18:36

import api.models.quiz
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_quiz_id_alter_sharedquiz_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.CharField(default=api.models.quiz.generate_quiz_id, editable=False, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sharedquiz',
            name='id',
            field=models.CharField(default='shc7b7b338fe4048389e9220250120183639998285', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='uc362707977be4369bac620250120183639982283', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
