# Generated by Django 5.1.2 on 2024-11-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_quiz_question_time_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allow_previous_questions',
            field=models.BooleanField(default=False),
        ),
    ]
