# Generated by Django 5.1.2 on 2024-10-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option_e',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
