# Generated by Django 5.1.2 on 2025-01-23 06:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_quiz_id_alter_sharedquiz_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedquiz',
            name='id',
            field=models.CharField(default='shee122901202501230615', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='u51c8baf6202501230615', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='QuizEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('event_type', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.quiz')),
            ],
        ),
    ]
