# Generated by Django 5.1.2 on 2025-01-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_quiz_access_control_alter_quiz_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.CharField(default='qe5d53e40ba340e5b6f12f01e70ad339', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='ufbc1ecb6a4c453db7ceb75a038dba4f', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
