# Generated by Django 5.1.2 on 2024-11-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_account_owner_accountmembership_account_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='subscription_plan',
            field=models.CharField(default='Free Plan', max_length=100),
        ),
        migrations.AddField(
            model_name='accountmembership',
            name='last_connected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=50),
        ),
    ]
