# Generated by Django 5.1.2 on 2024-10-12 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_question_option_d_question_option_e'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresult',
            old_name='created_at',
            new_name='completed_at',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_editable',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_shared',
        ),
        migrations.RemoveField(
            model_name='sharedquiz',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='userresult',
            name='total_questions',
        ),
        migrations.RemoveField(
            model_name='userresult',
            name='user_name',
        ),
        migrations.AddField(
            model_name='quiz',
            name='allow_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='display_results',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='require_name',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='require_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharedquiz',
            name='requires_authentication',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sharedquiz',
            name='share_link',
            field=models.URLField(default='https://example.com/placeholder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userresult',
            name='anonymous_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userresult',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sharedquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_quizzes', to='api.quiz'),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.quiz'),
        ),
    ]
