# Generated by Django 5.1.2 on 2025-01-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_quiz_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.CharField(default='qe53c21205254c1babd4a278aeb825eb', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sharedquiz',
            name='id',
            field=models.CharField(default='sh7fd768cb274944aef2183fb37ce117', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='uc1552073179464283d29e028efe3581', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
