# Generated by Django 5.1.2 on 2025-01-19 19:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_quiz_id_alter_sharedquiz_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.CharField(default='q432e99ca0e5f406aa6a11928b6a1c015', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sharedquiz',
            name='id',
            field=models.CharField(default='shfeea1a8555c3478180199b785bc29ed1', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='u32538f0ea56a4f458cb799729b83814f', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_authenticated_user', models.BooleanField(default=False)),
                ('external_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('has_completed', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.quiz')),
            ],
        ),
    ]
