# Generated by Django 5.1.2 on 2025-01-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_sharedquiz_id_alter_user_id_quizsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedquiz',
            name='id',
            field=models.CharField(default='sh3010c4f0202501260728', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='u24a45956202501260728', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
