# Generated by Django 5.1.2 on 2024-10-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_group_remove_quiz_quiz_type_quiz_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(default='multiple-choice', max_length=50),
        ),
    ]
