# Generated by Django 5.1.2 on 2025-01-15 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_last_connected_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='account',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='api.account'),
            preserve_default=False,
        ),
    ]
