# Generated by Django 5.1.2 on 2025-01-15 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_quiz_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='account',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.account'),
            preserve_default=False,
        ),
    ]
