# Generated by Django 5.1.2 on 2025-01-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_sharedquiz_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allow_review',
            field=models.BooleanField(default=True, help_text='Allow participants to review their answers after completion'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='review_window',
            field=models.IntegerField(blank=True, help_text='Number of days participants can review their answers (null for unlimited)', null=True),
        ),
        migrations.AlterField(
            model_name='sharedquiz',
            name='id',
            field=models.CharField(default='sh5d59a92a202501310224', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='ucd71bee2202501310224', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
