# Generated by Django 5.1.2 on 2025-01-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_quiz_allow_review_quiz_review_window_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedquiz',
            name='id',
            field=models.CharField(default='sh00dd2ff6202501312007', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='u740c4d4a202501312007', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
