# Generated by Django 5.1.2 on 2025-01-31 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_sharedquiz_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedquiz',
            name='id',
            field=models.CharField(default='shccb1b2d2202501312248', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='u9c125380202501312248', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
