# Generated by Django 5.1.2 on 2025-02-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_sharedquiz_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sharedquiz',
            name='id',
            field=models.CharField(default='sh49a6ef3f202502010427', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='u9b8642fd202502010427', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('quiz', 'email')},
        ),
    ]
