# Generated by Django 5.1.2 on 2025-02-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_participant_updated_at_alter_participant_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedquiz',
            name='id',
            field=models.CharField(default='sh799549f6202502010435', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='u7b6610a1202502010435', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
