# Generated by Django 5.1.2 on 2025-02-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_sharedquiz_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedquiz',
            name='id',
            field=models.CharField(default='she091c79b202502010448', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='uf71a6edb202502010448', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
