# Generated by Django 5.1.2 on 2025-02-01 18:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_sharedquiz_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizsubmission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='answers',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.participant'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sharedquiz',
            name='id',
            field=models.CharField(default='shb157363d202502011818', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='ubc482e74202502011818', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='QuizParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('has_completed', models.BooleanField(default=False)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_participations', to='api.participant')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='api.quiz')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('participant', 'quiz')},
            },
        ),
        migrations.AddField(
            model_name='quizsubmission',
            name='participation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.quizparticipation'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='participant',
            name='final_score',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='has_completed',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='responded_at',
        ),
    ]
