# Generated by Django 5.1.2 on 2025-02-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_quizsubmission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedquiz',
            name='id',
            field=models.CharField(default='shbcfe7c7e202502020105', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='u0cad4eb3202502020105', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
