# Generated by Django 5.1.2 on 2025-02-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_sharedquiz_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedquiz',
            name='id',
            field=models.CharField(default='sh84aad2b6202502050030', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default='ua81c2c03202502050030', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
